title: "Tell2U"
description: "Справочник"
baseurl: ""
url: "https://tell2u.ru"

author:
  name: "Katrovsky"
  email: "katrovskykirill@gmail.com"

remote_theme: just-the-docs/just-the-docs

color_scheme: nil

search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

nav_sort: case_insensitive

# aux_links:
#   "Tell2U на GitHub":
#     - "//github.com/katrovsky/katrovsky.github.io"

aux_links_new_tab: true

back_to_top: true
back_to_top_text: "Наверх"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

footer_content: "Copyright &copy; 2025 Katrovsky. Распространяется под лицензией MIT."

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

exclude:
  - README.md
  - LICENSE.txt
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Важно
    color: blue
  new:
    title: Новое
    color: green
  note:
    title: Заметка
    color: purple
  warning:
    title: Внимание
    color: red

#nav_external_links:
#  - title: GitHub репозиторий
#    url: https://github.com/katrovsky/katrovsky.github.io