site_name: Stranded
site_url: https://katrovsky.github.io/
site_description: Вики для курьеров СберМаркета.
site_author: Кирилл Катровский
nav:
  - Главная: index.md
  - О сайте: about.md
  - Контакты: contact.md

theme:
  name: material
  icon:
    logo: material/library
  language: ru
  features:
   - navigation.instant
   - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.top
  

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Светлый режим

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Тёмный режим

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Цветовая схема устройства

copyright: Copyright &copy; 2024 Kirill K.
extra:
  generator: false

# plugins:
#   - info
#   - social:
#       enabled: true
#       cards: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences